# Generated by Django 3.0.6 on 2020-05-27 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0003_brainstorm_brainstormresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainstormresponse',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='threads.BrainstormResponse'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BrainstormRespResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('brainstorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.Brainstorm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.BrainstormResponse')),
            ],
        ),
    ]
