# Generated by Django 3.0.6 on 2020-05-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20200527_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrainstormRespResponse',
        ),
    ]
