# Generated by Django 3.0.6 on 2020-06-04 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0005_delete_brainstormrespresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brainstormresponse',
            name='parent',
        ),
        migrations.AddField(
            model_name='brainstorm',
            name='brainstormresponses',
            field=models.ManyToManyField(related_name='thread_brainstormresponses', through='threads.BrainstormResponse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brainstorm',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='brainstormresponse',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reaction',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='response',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brainresponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.BrainstormResponse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrainstormComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('brainstormresponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.BrainstormResponse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='brainstormresponse',
            name='comments',
            field=models.ManyToManyField(related_name='thread_brainstormresponsecomments', through='threads.BrainstormComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brainstormresponse',
            name='votes',
            field=models.ManyToManyField(related_name='thread_brainstormresponsevotes', through='threads.Vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
