# Generated by Django 3.0.6 on 2020-07-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0012_auto_20200707_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='vieweddiscussionreply',
            name='last_seen',
            field=models.IntegerField(default=0),
        ),
    ]
